import {
  defineNexusPlugin,
  type WorkspaceDefinition,
} from "../core/plugin-sdk";

export const builtinPlugins = [
  defineNexusPlugin({
    id: "nexus.voice",
    name: "Voice Core",
    version: "0.3.0",
    apiVersion: "1",
    permissions: ["microphone"],
    widgets: [
      {
        id: "voice.core",
        title: "语音交互核心",
        kind: "voice",
        source: "MIC / REALTIME",
        defaultSize: { w: 6, h: 6 },
      },
    ],
    actions: [
      {
        id: "voice.toggle",
        title: "切换语音",
        voiceExamples: ["开始聆听", "停止聆听"],
      },
    ],
  }),
  defineNexusPlugin({
    id: "nexus.agents",
    name: "Agent Bridge",
    version: "0.3.0",
    apiVersion: "1",
    permissions: ["agent:delegate"],
    widgets: [
      {
        id: "agents.status",
        title: "智能体矩阵",
        kind: "agents",
        source: "ADAPTERS",
        defaultSize: { w: 4, h: 4 },
      },
    ],
    actions: [
      {
        id: "agent.delegate",
        title: "派发任务",
        voiceExamples: ["交给 Hermes", "让 Codex 处理"],
      },
    ],
  }),
  defineNexusPlugin({
    id: "nexus.telemetry",
    name: "Telemetry",
    version: "0.3.0",
    apiVersion: "1",
    permissions: ["system:metrics", "usage:read"],
    widgets: [
      {
        id: "system.metrics",
        title: "电脑状态监控",
        kind: "metrics",
        source: "LOCAL SYSTEM",
        defaultSize: { w: 4, h: 4 },
      },
      {
        id: "model.usage",
        title: "大模型 API 用量",
        kind: "usage",
        source: "REAL USAGE LEDGER",
        defaultSize: { w: 6, h: 5 },
      },
    ],
    actions: [],
  }),
  defineNexusPlugin({
    id: "nexus.timeline",
    name: "Event Stream",
    version: "0.3.0",
    apiVersion: "1",
    permissions: [],
    widgets: [
      {
        id: "event.timeline",
        title: "事件时间线",
        kind: "timeline",
        source: "EVENT BUS",
        defaultSize: { w: 6, h: 4 },
      },
    ],
    actions: [],
  }),
  defineNexusPlugin({
    id: "nexus.registry",
    name: "Plugin Registry",
    version: "0.3.0",
    apiVersion: "1",
    permissions: ["plugin:read"],
    widgets: [
      {
        id: "plugin.registry",
        title: "扩展组件",
        kind: "plugins",
        source: "PLUGIN API v1",
        defaultSize: { w: 6, h: 4 },
      },
    ],
    actions: [
      {
        id: "workspace.switch",
        title: "切换工作空间",
        voiceExamples: ["切换到开发模式"],
      },
    ],
  }),
  defineNexusPlugin({
    id: "nexus.productivity",
    name: "Productivity Suite",
    version: "0.3.0",
    apiVersion: "1",
    permissions: ["storage:plugin"],
    widgets: [
      {
        id: "productivity.calendar",
        title: "阴阳合历 · 万年历",
        kind: "calendar",
        source: "SOLAR + LUNAR",
        defaultSize: { w: 5, h: 6 },
      },
      {
        id: "productivity.memo",
        title: "备忘录",
        kind: "memo",
        source: "LOCAL",
        defaultSize: { w: 4, h: 4 },
      },
      {
        id: "productivity.planner",
        title: "计划管理",
        kind: "planner",
        source: "LOCAL",
        defaultSize: { w: 4, h: 4 },
      },
      {
        id: "productivity.chat",
        title: "对话与历史消息",
        kind: "chat",
        source: "HISTORY",
        defaultSize: { w: 6, h: 5 },
      },
      {
        id: "productivity.taskbar",
        title: "任务栏",
        kind: "taskbar",
        source: "TASK QUEUE",
        defaultSize: { w: 7, h: 3 },
      },
      {
        id: "intelligence.hotspots",
        title: "热点监控",
        kind: "hotspots",
        source: "WATCHLIST",
        defaultSize: { w: 6, h: 5 },
      },
    ],
    actions: [
      {
        id: "memo.create",
        title: "创建备忘",
        voiceExamples: ["记一个", "新建备忘"],
      },
      {
        id: "plan.create",
        title: "创建计划",
        voiceExamples: ["添加计划", "安排任务"],
      },
      {
        id: "hotspot.watch",
        title: "监控关键词",
        voiceExamples: ["监控这个关键词"],
      },
    ],
  }),
  defineNexusPlugin({
    id: "nexus.obsidian",
    name: "Obsidian Bridge",
    version: "0.3.0",
    apiVersion: "1",
    permissions: ["filesystem:user-selected"],
    widgets: [
      {
        id: "knowledge.obsidian-graph",
        title: "Obsidian 知识关系图",
        kind: "obsidian",
        source: "LOCAL VAULT",
        defaultSize: { w: 7, h: 6 },
      },
    ],
    actions: [
      {
        id: "obsidian.search",
        title: "搜索本地知识库",
        voiceExamples: ["搜索我的知识库", "打开知识关系图"],
      },
    ],
  }),
  defineNexusPlugin({
    id: "nexus.observability",
    name: "Observability Center",
    version: "0.3.0",
    apiVersion: "1",
    permissions: ["health:read", "connection:repair"],
    widgets: [
      {
        id: "observability.activity-log",
        title: "行动日志",
        kind: "activitylog",
        source: "AUDIT",
        defaultSize: { w: 8, h: 3 },
      },
      {
        id: "observability.trace",
        title: "执行思路",
        kind: "trace",
        source: "EXPLAINABLE",
        defaultSize: { w: 6, h: 4 },
      },
      {
        id: "observability.heartbeat",
        title: "心跳与自动修复",
        kind: "heartbeat",
        source: "HEALTH",
        defaultSize: { w: 4, h: 3 },
      },
      {
        id: "observability.connections",
        title: "真实连接中心",
        kind: "connections",
        source: "LIVE PROBE",
        defaultSize: { w: 5, h: 5 },
      },
    ],
    actions: [
      {
        id: "health.repair",
        title: "修复服务连接",
        voiceExamples: ["检查连接", "修复断开的连接"],
      },
    ],
  }),
  defineNexusPlugin({
    id: "nexus.feishu",
    name: "Feishu Connector",
    version: "0.3.0",
    apiVersion: "1",
    permissions: ["network:feishu", "secret:feishu"],
    widgets: [
      {
        id: "collaboration.feishu",
        title: "飞书协作中枢",
        kind: "feishu",
        source: "FEISHU OPEN API",
        defaultSize: { w: 7, h: 6 },
      },
    ],
    actions: [
      {
        id: "feishu.sync",
        title: "同步飞书",
        voiceExamples: ["同步飞书", "读取我的飞书计划"],
      },
    ],
  }),
  defineNexusPlugin({
    id: "nexus.avatar",
    name: "Avatar Stage",
    version: "0.3.0",
    apiVersion: "1",
    permissions: ["media:user-selected", "voice:state"],
    widgets: [
      {
        id: "avatar.stage",
        title: "数字人交互舞台",
        kind: "avatar",
        source: "AVATAR RUNTIME",
        defaultSize: { w: 4, h: 6 },
      },
    ],
    actions: [
      {
        id: "avatar.expression",
        title: "切换角色表情",
        voiceExamples: ["让角色开心一点", "切换机器人"],
      },
    ],
  }),
  defineNexusPlugin({
    id: "nexus.agentworld",
    name: "Agent World",
    version: "0.3.0",
    apiVersion: "1",
    permissions: ["task:event:read"],
    widgets: [
      {
        id: "agents.world-2d",
        title: "智能体 2D 作业空间",
        kind: "agentworld",
        source: "LIVE TASK MAP",
        defaultSize: { w: 8, h: 7 },
      },
    ],
    actions: [
      {
        id: "agentworld.focus",
        title: "聚焦智能体",
        voiceExamples: ["看看 Hermes 在做什么", "打开工作空间"],
      },
    ],
  }),
  defineNexusPlugin({
    id: "nexus.decor",
    name: "Decor Modules",
    version: "0.3.0",
    apiVersion: "1",
    permissions: [],
    widgets: [
      {
        id: "decor.orbital-radar",
        title: "轨道装饰雷达",
        kind: "decoration",
        source: "AMBIENT",
        defaultSize: { w: 3, h: 3 },
      },
    ],
    actions: [],
  }),
];

export const workspacePresets: WorkspaceDefinition[] = [
  {
    id: "command-center",
    name: "指挥中心",
    shortName: "COMMAND",
    theme: "cyan",
    widgets: [
      {
        instanceId: "voice-1",
        widgetId: "voice.core",
        x: 0,
        y: 0,
        w: 6,
        h: 6,
        layer: 2,
      },
      {
        instanceId: "avatar-1",
        widgetId: "avatar.stage",
        x: 6,
        y: 0,
        w: 3,
        h: 6,
        floating: true,
        layer: 3,
      },
      {
        instanceId: "connections-1",
        widgetId: "observability.connections",
        x: 9,
        y: 0,
        w: 3,
        h: 6,
        layer: 2,
      },
      {
        instanceId: "taskbar-1",
        widgetId: "productivity.taskbar",
        x: 6,
        y: 6,
        w: 6,
        h: 2,
        layer: 1,
      },
      {
        instanceId: "calendar-1",
        widgetId: "productivity.calendar",
        x: 0,
        y: 8,
        w: 5,
        h: 6,
        layer: 1,
      },
      {
        instanceId: "planner-1",
        widgetId: "productivity.planner",
        x: 5,
        y: 8,
        w: 4,
        h: 6,
        layer: 1,
      },
      {
        instanceId: "heartbeat-1",
        widgetId: "observability.heartbeat",
        x: 9,
        y: 8,
        w: 3,
        h: 3,
        layer: 1,
      },
      {
        instanceId: "decor-1",
        widgetId: "decor.orbital-radar",
        x: 9,
        y: 11,
        w: 3,
        h: 3,
        floating: true,
        layer: 3,
      },
    ],
  },
  {
    id: "development",
    name: "开发工作台",
    shortName: "DEVELOPMENT",
    theme: "violet",
    widgets: [
      {
        instanceId: "agents-dev",
        widgetId: "agents.status",
        x: 0,
        y: 0,
        w: 4,
        h: 5,
        layer: 1,
      },
      {
        instanceId: "chat-dev",
        widgetId: "productivity.chat",
        x: 4,
        y: 0,
        w: 8,
        h: 6,
        layer: 2,
      },
      {
        instanceId: "timeline-dev",
        widgetId: "event.timeline",
        x: 0,
        y: 5,
        w: 4,
        h: 5,
        layer: 1,
      },
      {
        instanceId: "trace-dev",
        widgetId: "observability.trace",
        x: 4,
        y: 6,
        w: 4,
        h: 4,
        layer: 1,
      },
      {
        instanceId: "heartbeat-dev",
        widgetId: "observability.heartbeat",
        x: 8,
        y: 6,
        w: 4,
        h: 4,
        layer: 1,
      },
      {
        instanceId: "world-dev",
        widgetId: "agents.world-2d",
        x: 0,
        y: 10,
        w: 12,
        h: 7,
        layer: 1,
      },
      {
        instanceId: "usage-dev",
        widgetId: "model.usage",
        x: 0,
        y: 17,
        w: 12,
        h: 5,
        layer: 1,
      },
    ],
  },
  {
    id: "intelligence",
    name: "情报中心",
    shortName: "INTELLIGENCE",
    theme: "amber",
    widgets: [
      {
        instanceId: "hotspots-intel",
        widgetId: "intelligence.hotspots",
        x: 0,
        y: 0,
        w: 7,
        h: 6,
        layer: 1,
      },
      {
        instanceId: "calendar-intel",
        widgetId: "productivity.calendar",
        x: 7,
        y: 0,
        w: 5,
        h: 6,
        layer: 1,
      },
      {
        instanceId: "obsidian-intel",
        widgetId: "knowledge.obsidian-graph",
        x: 0,
        y: 6,
        w: 8,
        h: 6,
        layer: 1,
      },
      {
        instanceId: "memo-intel",
        widgetId: "productivity.memo",
        x: 8,
        y: 6,
        w: 4,
        h: 6,
        layer: 1,
      },
    ],
  },
  {
    id: "collaboration",
    name: "协作空间",
    shortName: "COLLAB",
    theme: "starfleet",
    widgets: [
      {
        instanceId: "feishu-main",
        widgetId: "collaboration.feishu",
        x: 0,
        y: 0,
        w: 7,
        h: 7,
        layer: 2,
      },
      {
        instanceId: "calendar-collab",
        widgetId: "productivity.calendar",
        x: 7,
        y: 0,
        w: 5,
        h: 7,
        layer: 1,
      },
      {
        instanceId: "planner-collab",
        widgetId: "productivity.planner",
        x: 0,
        y: 7,
        w: 5,
        h: 5,
        layer: 1,
      },
      {
        instanceId: "connections-collab",
        widgetId: "observability.connections",
        x: 5,
        y: 7,
        w: 4,
        h: 5,
        layer: 1,
      },
      {
        instanceId: "activity-collab",
        widgetId: "observability.activity-log",
        x: 9,
        y: 7,
        w: 3,
        h: 5,
        layer: 1,
      },
    ],
  },
];

export const defaultWorkspace = workspacePresets[0];
